# Random Forest Classification

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject          Activity
0              0.288585          -0.020294  ...        1          STANDING
1              0.278419          -0.016411  ...        1          STANDING
2              0.279653          -0.019467  ...        1          STANDING
3              0.279174          -0.026201  ...        1          STANDING
4              0.276629          -0.016570  ...        1          STANDING
...                 ...                ...  ...      ...               ...
7347           0.299665          -0.057193  ...       30  WALKING_UPSTAIRS
7348           0.273853          -0.007749  ...       30  WALKING_UPSTAIRS
7349           0.273387          -0.017011  ...       30  WALKING_UPSTAIRS
7350           0.289654          -0.018843  ...       30  WALKING_UPSTAIRS
7351           0.351503          -0.012423  ...       30  WALKING_UPSTAIRS

[7352 rows x 563 columns]

In [4]:
test

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject          Activity
0              0.257178          -0.023285  ...        2          STANDING
1              0.286027          -0.013163  ...        2          STANDING
2              0.275485          -0.026050  ...        2          STANDING
3              0.270298          -0.032614  ...        2          STANDING
4              0.274833          -0.027848  ...        2          STANDING
...                 ...                ...  ...      ...               ...
2942           0.310155          -0.053391  ...       24  WALKING_UPSTAIRS
2943           0.363385          -0.039214  ...       24  WALKING_UPSTAIRS
2944           0.349966           0.030077  ...       24  WALKING_UPSTAIRS
2945           0.237594           0.018467  ...       24  WALKING_UPSTAIRS
2946           0.153627          -0.018437  ...       24  WALKING_UPSTAIRS

[2947 rows x 563 columns]

## Splitting the dataset into the Training set and Test set

In [0]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, 562].values
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, 562].values

## Encoding y data


In [0]:
from sklearn.preprocessing import LabelEncoder
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [7]:
y_train

array([2, 2, 2, ..., 5, 5, 5])

In [8]:
y_test

array([2, 2, 2, ..., 5, 5, 5])

## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 0.20064157, -0.0636826 , -0.41962845, ...,  0.40794614,
        -0.00756789, -1.8288513 ],
       [ 0.05594788,  0.03148567, -0.25390836, ...,  0.40911698,
         0.00787517, -1.8288513 ],
       [ 0.07351535, -0.04341648, -0.07629468, ...,  0.4102883 ,
         0.02650234, -1.8288513 ],
       ...,
       [-0.01566765,  0.0167814 ,  1.13222107, ...,  0.64059683,
         0.34870928,  1.4025149 ],
       [ 0.21586648, -0.02812252, -0.86770988, ...,  0.63147758,
         0.29327564,  1.4025149 ],
       [ 1.09620157,  0.12919873, -1.67268082, ...,  0.63274259,
         0.33396081,  1.4025149 ]])

In [11]:
X_test

array([[-0.24638762, -0.13697895,  1.66846245, ...,  0.73357141,
        -0.00524394, -1.71742488],
       [ 0.164235  ,  0.11105901, -0.17554768, ...,  0.7488403 ,
        -0.09811176, -1.71742488],
       [ 0.01418651, -0.20474035, -0.15911067, ...,  0.7446048 ,
        -0.08180304, -1.71742488],
       ...,
       [ 1.0743192 ,  1.17068132, -0.11737212, ...,  0.72576444,
         0.85164992,  0.73395638],
       [-0.5251367 ,  0.88616251,  0.22323486, ...,  0.69316451,
         0.87450655,  0.73395638],
       [-1.72027986, -0.01816024, -0.49226174, ...,  0.69032237,
         0.87644307,  0.73395638]])

## Training the Random Forest Classification model on the Training set

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Making the Confusion Matrix, printing accuracy and classification report

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix : ")
print(cm)
print(" ")
print("Accuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))
print(" ")
print("Classification report: ")
print(classification_report(y_test, y_pred))

Confusion matrix : 
[[537   0   0   0   0   0]
 [  0 442  49   0   0   0]
 [  0  50 482   0   0   0]
 [  0   0   0 482   8   6]
 [  0   0   0  23 352  45]
 [  0   0   0  81  10 380]]
 
Accuracy: 90.77 %
 
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       537
           1       0.90      0.90      0.90       491
           2       0.91      0.91      0.91       532
           3       0.82      0.97      0.89       496
           4       0.95      0.84      0.89       420
           5       0.88      0.81      0.84       471

    accuracy                           0.91      2947
   macro avg       0.91      0.90      0.91      2947
weighted avg       0.91      0.91      0.91      2947



## Applying k-Fold Cross Validation

In [14]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 92.40 %
Standard Deviation: 3.14 %


## Applying Grid Search to find the best model and the best parameters

In [16]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators': [10,25, 50, 100], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 93.81 %
Best Parameters: {'max_depth': 30, 'n_estimators': 100}
